version: '3.8'

services:
  db: 
    image: postgres:15
    container_name: home_finance_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:  
      - postgres_data:/var/lib/postgresql/data
    networks:
      - localnet
volumes:
  postgres_data:
networks:
  localnet: