"""Create table_category and user_table tables

Revision ID: 081c9d89da2e
Revises: ddfd0bad9f6e
Create Date: 2025-07-20 13:01:01.687092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '081c9d89da2e'
down_revision: Union[str, None] = 'ddfd0bad9f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_category',
    sa.Column('table_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ),
    sa.PrimaryKeyConstraint('table_id', 'category_id')
    )
    op.create_table('user_table',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('table_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'table_id')
    )
    op.add_column('table', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'table', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'table', type_='foreignkey')
    op.drop_column('table', 'user_id')
    op.drop_table('user_table')
    op.drop_table('table_category')
    # ### end Alembic commands ###
