"""Create base fields on associations

Revision ID: 516b7cc7b668
Revises: 081c9d89da2e
Create Date: 2025-07-20 13:06:56.534474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '516b7cc7b668'
down_revision: Union[str, None] = '081c9d89da2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_category', sa.Column('id', sa.String(length=36), nullable=False))
    op.add_column('table_category', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('table_category', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('table_category', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('table_category', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('table_category', sa.Column('updated_by', sa.String(), nullable=False))
    op.add_column('table_category', sa.Column('deleted_by', sa.String(), nullable=True))
    op.create_index(op.f('ix_table_category_id'), 'table_category', ['id'], unique=False)
    op.add_column('user_table', sa.Column('id', sa.String(length=36), nullable=False))
    op.add_column('user_table', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('user_table', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('user_table', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('user_table', sa.Column('created_by', sa.String(), nullable=False))
    op.add_column('user_table', sa.Column('updated_by', sa.String(), nullable=False))
    op.add_column('user_table', sa.Column('deleted_by', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_table_id'), 'user_table', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_table_id'), table_name='user_table')
    op.drop_column('user_table', 'deleted_by')
    op.drop_column('user_table', 'updated_by')
    op.drop_column('user_table', 'created_by')
    op.drop_column('user_table', 'deleted_at')
    op.drop_column('user_table', 'updated_at')
    op.drop_column('user_table', 'created_at')
    op.drop_column('user_table', 'id')
    op.drop_index(op.f('ix_table_category_id'), table_name='table_category')
    op.drop_column('table_category', 'deleted_by')
    op.drop_column('table_category', 'updated_by')
    op.drop_column('table_category', 'created_by')
    op.drop_column('table_category', 'deleted_at')
    op.drop_column('table_category', 'updated_at')
    op.drop_column('table_category', 'created_at')
    op.drop_column('table_category', 'id')
    # ### end Alembic commands ###
