"""update relations

Revision ID: 942e5ee9cbe4
Revises: edeae18e37b7
Create Date: 2025-07-20 19:13:36.277202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '942e5ee9cbe4'
down_revision: Union[str, None] = 'edeae18e37b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('table_category', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('table_category', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index('ix_table_category_id', table_name='table_category')
    op.drop_column('table_category', 'deleted_by')
    op.drop_column('table_category', 'updated_by')
    op.drop_column('table_category', 'created_by')
    op.drop_column('table_category', 'id')
    op.drop_column('table_category', 'deleted_at')
    op.alter_column('user_table', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('user_table', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index('ix_user_table_id', table_name='user_table')
    op.drop_column('user_table', 'deleted_by')
    op.drop_column('user_table', 'updated_by')
    op.drop_column('user_table', 'created_by')
    op.drop_column('user_table', 'id')
    op.drop_column('user_table', 'deleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user_table', sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('user_table', sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_table', sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_table', sa.Column('deleted_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_user_table_id', 'user_table', ['id'], unique=False)
    op.alter_column('user_table', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('user_table', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('table_category', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('table_category', sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('table_category', sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('table_category', sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('table_category', sa.Column('deleted_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_table_category_id', 'table_category', ['id'], unique=False)
    op.alter_column('table_category', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('table_category', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
