"""Make log fields nullable

Revision ID: edeae18e37b7
Revises: 516b7cc7b668
Create Date: 2025-07-20 18:59:10.149320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edeae18e37b7'
down_revision: Union[str, None] = '516b7cc7b668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('category', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('entry', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('entry', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('entry_user_percentage', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('entry_user_percentage', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('table', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('table', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('table_category', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('table_category', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_table', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_table', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_table', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_table', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('table_category', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('table_category', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('table', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('table', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('entry_user_percentage', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('entry_user_percentage', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('entry', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('entry', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('category', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('category', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
