"""Corrige relacionamento entries-category

Revision ID: f65e454d61e0
Revises: c9e1069ee811
Create Date: 2025-07-15 00:02:53.624160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f65e454d61e0'
down_revision: Union[str, None] = 'c9e1069ee811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
